name:  Dev Report
description: Template para reportar historias de usuario con criterios de aceptaci贸n y tareas de desarrollo
title: "[HU]: "
labels: ["dev", "enhancement"]
body:
  - type: textarea
    id: user-story
    attributes:
      label: Historia de Usuario
      description: Describe la funcionalidad desde la perspectiva del usuario final
      value: |
        **Como** _visitante_
        **Quiero** entender de inmediato la propuesta de valor y tener un camino claro para unirme
        **Para** convertir mi inter茅s en una acci贸n concreta (unirme/colaborar) sin fricci贸n ni dudas
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## Criterios de Aceptaci贸n
        Define las condiciones que deben cumplirse para considerar completada esta historia.

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Criterios de Aceptaci贸n
      description: Lista los criterios que deben cumplirse
      value: |
        - [ ] 
        - [ ] 
        - [ ]
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## Tareas de Desarrollo

  - type: textarea
    id: dev-tasks
    attributes:
      label: Tareas
      description: Lista de tareas t茅cnicas para implementar la historia
      value: |
        - [ ] 
        - [ ] 
        - [ ]
    validations:
      required: true

  - type: textarea
    id: technical-details
    attributes:
      label: Detalles T茅cnicos
      description: Informaci贸n t茅cnica relevante, tecnolog铆as, componentes, o consideraciones especiales
      placeholder: "Componentes a usar: HeroSection.astro\nDise帽o: Penpot (Hero/Nav/Foot)\nLinks: Discord (permanente), Repo"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notas Adicionales
      description: Cualquier informaci贸n adicional o contexto relevante
      placeholder: "A帽ade contexto, referencias, o consideraciones especiales..."
    validations:
      required: false
